version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "infra"

  - package-ecosystem: "npm"
    directory: "/portal"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "portal"

  - package-ecosystem: "docker"
    directory: "/compose"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:45"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "runtime"
