all:
  children:
    vps_baseline_vps:
      hosts:
        vps.nutsnews.com:
          ansible_host: 65.75.202.112
          vps_baseline_ipv4: 65.75.202.112
          vps_baseline_ipv6: "2606:cc0:11:23ae::1"
          vps_baseline_os: Ubuntu 26.04 LTS
          vps_baseline_vcpu: 4
          vps_baseline_memory_mib: 10240
          vps_baseline_disk_gib: 80
