- name: Restart systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Validate sshd configuration
  ansible.builtin.command: sshd -t
  changed_when: false
  listen: Reload ssh

- name: Reload ssh
  ansible.builtin.service:
    name: ssh
    state: reloaded
  listen: Reload ssh
